---
- name: This is a recipe for how to cook with packit-service
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
    packit_service_path: /src
  tasks:
    - name: check source_branch
      debug:
        msg: SOURCE_BRANCH is set to {{ source_branch }}
    - name: install ogr
      pip:
        name:
          - git+https://github.com/packit-service/ogr.git@{{ source_branch }}
        extra_args: --no-deps
