FROM sakalosj/packit-deployment-test:test


COPY install-deps-github.yaml /src/

RUN cd /src/ \
    && ansible-playbook -vv -c local -i localhost, install-deps-github.yaml \
    && dnf -y clean all --enablerepo='*'

