# Image for the web service (httpd), for celery worker see Dockerfile.worker

FROM docker.io/sakalosj/github_base:test

ARG SOURCE_BRANCH

ENV LANG=en_US.UTF-8 \
    USER=packit \
    ANSIBLE_STDOUT_CALLBACK=debug \
    HOME=/home/packit 

COPY files/setup.py files/setup.cfg files/recipe.yaml files/httpd.yaml files/common.yaml files/packit.wsgi files/run_httpd.sh files/setup_env_in_openshift.sh files/packit-httpd.conf /src/

RUN env

RUN cd /src/ \
   && ansible-playbook -vv -c local -i localhost, --extra-vars "source_branch=$SOURCE_BRANCH" recipe.yaml

CMD ["echo test build done"]
