---
- name: Install dependencies for packit-service.
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run packit-service.
      dnf:
        name:
          - git # setuptools-scm
          # httpd & deps
          - httpd
          - mod_md
          - mod_ssl
          - nss_wrapper
          #- python3-packit # temporary workaround for sake of marhsmallow
          - python3-pip # not included in base fedora:31 image, needed for next task
          - python3-devel
          # temporary dependencies
          - krb5-devel
          - gcc
          # (see d90948124e46_add_tables_for_triggers_koji_and_tests.py )
        state: present
    - name: Install pip deps
      pip:
        name:
          # temporary workaround for sake of marhsmallow
          - git+https://github.com/packit-service/packit.git
          - persistentdict # still needed by one Alembic migration script
          - sentry-sdk==0.14.4
          - sentry-sdk[flask]==0.14.4
          - flask-restx
          - sqlalchemy
          - redis
          - alembic
          - prometheus_client
          - psycopg2-binary
          - lazy-object-proxy
          - flexmock 
          - click
          - ipdb
        executable: pip3
